// Generated by Port/Build/shaders.py from pinned original HLSL.
Shader "SCUnity/Port/5d96d73eaeb9a733" {
Properties { _Cull("Cull",Float)=0 _Src("Source",Float)=1 _Dst("Destination",Float)=0 _SrcA("Source alpha",Float)=1 _DstA("Destination alpha",Float)=0 _ZWrite("Depth write",Float)=0 _ZTest("Depth test",Float)=8 }
SubShader { Tags {"RenderPipeline"="UniversalPipeline"} Pass {
Cull [_Cull] Blend [_Src] [_Dst], [_SrcA] [_DstA] ZWrite [_ZWrite] ZTest [_ZTest]
HLSLPROGRAM
#pragma target 4.5
#pragma vertex SCVert
#pragma fragment SCFrag

#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#define HLSL
#define MAX_INSTANCES_COUNT 64
#define MAX_JOINTS_COUNT 128
#if defined(SHADER_STAGE_VERTEX)
#ifdef HLSL

float2 u_origin;
float4x4 u_viewProjectionMatrix;
float3 u_viewPosition;
float u_fogYMultiplier;
float3 u_fogBottomTopDensity;
float2 u_hazeStartDensity;

float fogIntegral(float y)
{
	return smoothstep(u_fogBottomTopDensity.x, u_fogBottomTopDensity.y, y) * (u_fogBottomTopDensity.y - u_fogBottomTopDensity.x) + u_fogBottomTopDensity.x;
}

float calculateFog(float3 position)
{
	float3 fogDelta = u_viewPosition - position;
	fogDelta.y *= u_fogYMultiplier;
	float fogDistance = length(fogDelta);
	float fogFactor = (fogIntegral(u_viewPosition.y) - fogIntegral(position.y)) / (u_viewPosition.y - position.y);
	return saturate(saturate(u_hazeStartDensity.y * (fogDistance - u_hazeStartDensity.x)) + fogFactor * u_fogBottomTopDensity.z * fogDistance);
}

void SCVert(
	in float3 a_position: POSITION,
	in float4 a_color: COLOR,
	in float2 a_texcoord: TEXCOORD,
	out float4 v_color : COLOR,
	out float2 v_texcoord : TEXCOORD,
	out float v_fog : FOG,
	out float4 sv_position: SV_POSITION
)
{
	// Texture
	v_texcoord = a_texcoord;

	// Vertex color
	v_color = a_color;

	// Fog
	v_fog = calculateFog(a_position);

	// Position
	sv_position = mul(float4(a_position.x - u_origin.x, a_position.y, a_position.z - u_origin.y, 1.0), u_viewProjectionMatrix);
#if UNITY_REVERSED_Z
sv_position.z = sv_position.w - sv_position.z;
#endif
}

#endif
#ifdef GLSL

// <Semantic Name='POSITION' Attribute='a_position' />
// <Semantic Name='COLOR' Attribute='a_color' />
// <Semantic Name='TEXCOORD' Attribute='a_texcoord' />

uniform vec2 u_origin;
uniform mat4 u_viewProjectionMatrix;
uniform vec3 u_viewPosition;
uniform float u_fogYMultiplier;
uniform vec3 u_fogBottomTopDensity;
uniform vec2 u_hazeStartDensity;

attribute vec3 a_position;
attribute vec4 a_color;
attribute vec2 a_texcoord;

varying vec4 v_color;
varying vec2 v_texcoord;
varying float v_fog;

float fogIntegral(float y)
{
	return smoothstep(u_fogBottomTopDensity.x, u_fogBottomTopDensity.y, y) * (u_fogBottomTopDensity.y - u_fogBottomTopDensity.x) + u_fogBottomTopDensity.x;
}

float calculateFog(vec3 position)
{
	vec3 fogDelta = u_viewPosition - position;
	fogDelta.y *= u_fogYMultiplier;
	float fogDistance = length(fogDelta);
	float fogFactor = (fogIntegral(u_viewPosition.y) - fogIntegral(position.y)) / (u_viewPosition.y - position.y);
	return clamp(clamp(u_hazeStartDensity.y * (fogDistance - u_hazeStartDensity.x), 0.0, 1.0) + fogFactor * u_fogBottomTopDensity.z * fogDistance, 0.0, 1.0);
}

void SCVert()
{
	// Texture
	v_texcoord = a_texcoord;

	// Vertex color
	v_color = a_color;

	// Fog
	v_fog = calculateFog(a_position);

	// Position
	gl_Position = u_viewProjectionMatrix * vec4(a_position.x - u_origin.x, a_position.y, a_position.z - u_origin.y, 1.0);

	// Fix gl_Position
	OPENGL_POSITION_FIX;
}

#endif

#endif
#if defined(SHADER_STAGE_FRAGMENT)
#ifdef HLSL

Texture2D u_texture;
SamplerState sampler_u_texture;
float3 u_fogColor;

void SCFrag(
	in float4 v_color : COLOR,
	in float2 v_texcoord: TEXCOORD,
	in float v_fog : FOG,
	out float4 svTarget: SV_TARGET
)
{
	// Color
	float4 result = v_color;

	// Texture
	result *= u_texture.Sample(sampler_u_texture, v_texcoord);

	// Alpha threshold
	if (result.a <= 0.0)
		discard;

	// Highlight
	result.rgb = result.rgb * 1.2 + 0.05 * float3(1, 1, 1);

	// Fog
	float4 premultipliedFogColor = float4(u_fogColor * result.a, result.a);
	result = lerp(result, premultipliedFogColor, v_fog);

	// Return
	svTarget = result;
}

#endif
#ifdef GLSL

// <Sampler Name='sampler_u_texture' Texture='u_texture' />

#ifdef GL_ES
precision mediump float;
#endif

uniform sampler2D u_texture;
uniform vec3 u_fogColor;

varying vec4 v_color;
varying vec2 v_texcoord;
varying float v_fog;

void SCFrag()
{
	// Color
	vec4 result = v_color;

	// Texture
	result *= texture2D(u_texture, v_texcoord);

	// Alpha threshold
	if (result.a <= 0.0)
		discard;

	// Highlight
	result.rgb = result.rgb * 1.2 + 0.05 * vec3(1, 1, 1);

	// Fog
	vec4 premultipliedFogColor = vec4(u_fogColor * result.a, result.a);
	result = mix(result, premultipliedFogColor, v_fog);

	// Return
	gl_FragColor = result;
}

#endif
#endif
ENDHLSL
} }
}
