// Generated by Port/Build/shaders.py from pinned original HLSL.
Shader "SCUnity/Port/fa3c1133a449ed53" {
Properties { _Cull("Cull",Float)=0 _Src("Source",Float)=1 _Dst("Destination",Float)=0 _SrcA("Source alpha",Float)=1 _DstA("Destination alpha",Float)=0 _ZWrite("Depth write",Float)=0 _ZTest("Depth test",Float)=8 }
SubShader { Tags {"RenderPipeline"="UniversalPipeline"} Pass {
Cull [_Cull] Blend [_Src] [_Dst], [_SrcA] [_DstA] ZWrite [_ZWrite] ZTest [_ZTest]
HLSLPROGRAM
#pragma target 4.5
#pragma vertex SCVert
#pragma fragment SCFrag
#pragma multi_compile _ USE_ALPHATHRESHOLD
#pragma multi_compile _ USE_EMISSIONCOLOR
#pragma multi_compile _ USE_FOG
#pragma multi_compile _ USE_INSTANCING
#pragma multi_compile _ USE_TEXTURE
#pragma multi_compile _ USE_VERTEXCOLOR
#pragma multi_compile _ ONE_LIGHT TWO_LIGHTS THREE_LIGHTS
#if defined(ONE_LIGHT) || defined(TWO_LIGHTS) || defined(THREE_LIGHTS)
#define USE_LIGHTING
#endif
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Common.hlsl"
#define HLSL
#define MAX_INSTANCES_COUNT 64
#define MAX_JOINTS_COUNT 128
#if defined(SHADER_STAGE_VERTEX)
#ifdef HLSL

// Transform
#ifdef USE_INSTANCING
#ifdef USE_LIGHTING
float4x4 u_worldMatrix[MAX_INSTANCES_COUNT];
#endif
#ifdef USE_FOG
float4x4 u_worldViewMatrix[MAX_INSTANCES_COUNT];
#endif
float4x4 u_worldViewProjectionMatrix[MAX_INSTANCES_COUNT];
#else
#ifdef USE_LIGHTING
float4x4 u_worldMatrix;
#endif
#ifdef USE_FOG
float4x4 u_worldViewMatrix;
#endif
float4x4 u_worldViewProjectionMatrix;
#endif

// Material
float4 u_materialColor;

// Emission color
#ifdef USE_EMISSIONCOLOR
float4 u_emissionColor;
#endif

// Light
#ifdef ONE_LIGHT
float3 u_ambientLightColor;
float3 u_diffuseLightColor1;
float3 u_directionToLight1;
#endif
#ifdef TWO_LIGHTS
float3 u_ambientLightColor;
float3 u_diffuseLightColor1;
float3 u_directionToLight1;
float3 u_diffuseLightColor2;
float3 u_directionToLight2;
#endif
#ifdef THREE_LIGHTS
float3 u_ambientLightColor;
float3 u_diffuseLightColor1;
float3 u_directionToLight1;
float3 u_diffuseLightColor2;
float3 u_directionToLight2;
float3 u_diffuseLightColor3;
float3 u_directionToLight3;
#endif

// Fog
#ifdef USE_FOG
float u_fogStart;
float u_fogLength;
#endif

void SCVert(
	in float3 a_position: POSITION,
#ifdef USE_LIGHTING
	in float3 a_normal: NORMAL,
#endif
#ifdef USE_VERTEXCOLOR
	in float4 a_color: COLOR,
#endif
#ifdef USE_TEXTURE
	in float2 a_texcoord: TEXCOORD,
#endif
#ifdef USE_INSTANCING
	in float a_instance: TEXCOORD7,
#endif
	out float4 v_color : COLOR,
#ifdef USE_TEXTURE
	out float2 v_texcoord : TEXCOORD,
#endif
#ifdef USE_FOG
	out float v_fog : FOG,
#endif
	out float4 sv_position: SV_POSITION
)
{
	// Texture
#ifdef USE_TEXTURE
	v_texcoord = a_texcoord;
#endif

	// Instancing
#ifdef USE_INSTANCING
	int instance = int(a_instance);
#endif

	// Normal
#ifdef USE_LIGHTING
#ifdef USE_INSTANCING
	float3 worldNormal = normalize(mul(float4(a_normal, 0.0), u_worldMatrix[instance]).xyz);
#else
	float3 worldNormal = normalize(mul(float4(a_normal, 0.0), u_worldMatrix).xyz);
#endif
#endif

	// Lighting
#ifndef USE_LIGHTING
	v_color = u_materialColor;
#endif
#ifdef ONE_LIGHT
	float3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	v_color = float4(lightColor, 1) * u_materialColor;
#endif
#ifdef TWO_LIGHTS
	float3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	lightColor += u_diffuseLightColor2 * max(dot(u_directionToLight2, worldNormal), 0.0);
	v_color = float4(lightColor, 1) * u_materialColor;
#endif
#ifdef THREE_LIGHTS
	float3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	lightColor += u_diffuseLightColor2 * max(dot(u_directionToLight2, worldNormal), 0.0);
	lightColor += u_diffuseLightColor3 * max(dot(u_directionToLight3, worldNormal), 0.0);
	v_color = float4(lightColor, 1) * u_materialColor;
#endif

	// Vertex color
#ifdef USE_VERTEXCOLOR
	v_color *= a_color;
#endif

	// Emission color
#ifdef USE_EMISSIONCOLOR
	v_color += u_emissionColor;
#endif

	// Fog
#ifdef USE_FOG
#ifdef USE_INSTANCING
	float3 viewPosition = mul(float4(a_position, 1.0), u_worldViewMatrix[instance]).xyz;
#else
	float3 viewPosition = mul(float4(a_position, 1.0), u_worldViewMatrix).xyz;
#endif
	float d = length(viewPosition);
	v_fog = saturate((d - u_fogStart) / u_fogLength);
#endif

	// Position
#ifdef USE_INSTANCING
	sv_position = mul(float4(a_position, 1.0), u_worldViewProjectionMatrix[instance]);
#if UNITY_REVERSED_Z
sv_position.z = sv_position.w - sv_position.z;
#endif
#else
	sv_position = mul(float4(a_position, 1.0), u_worldViewProjectionMatrix);
#if UNITY_REVERSED_Z
sv_position.z = sv_position.w - sv_position.z;
#endif
#endif
}

#endif
#ifdef GLSL

// <Semantic Name='POSITION' Attribute='a_position' />
// <Semantic Name='NORMAL' Attribute='a_normal' />
// <Semantic Name='COLOR' Attribute='a_color' />
// <Semantic Name='TEXCOORD' Attribute='a_texcoord' />
// <Semantic Name='INSTANCE' Attribute='a_instance' />

// Transform
#ifdef USE_INSTANCING
#ifdef USE_LIGHTING
uniform mat4 u_worldMatrix[MAX_INSTANCES_COUNT];
#endif
uniform mat4 u_worldViewProjectionMatrix[MAX_INSTANCES_COUNT];
#ifdef USE_FOG
uniform mat4 u_worldViewMatrix[MAX_INSTANCES_COUNT];
#endif
#else
#ifdef USE_LIGHTING
uniform mat4 u_worldMatrix;
#endif
uniform mat4 u_worldViewProjectionMatrix;
#ifdef USE_FOG
uniform mat4 u_worldViewMatrix;
#endif
#endif

uniform vec4 u_materialColor;

// Emission color
#ifdef USE_EMISSIONCOLOR
uniform vec4 u_emissionColor;
#endif

// Material and light
#ifdef ONE_LIGHT
uniform vec3 u_ambientLightColor;
uniform vec3 u_diffuseLightColor1;
uniform vec3 u_directionToLight1;
#endif
#ifdef TWO_LIGHTS
uniform vec3 u_ambientLightColor;
uniform vec3 u_diffuseLightColor1;
uniform vec3 u_directionToLight1;
uniform vec3 u_diffuseLightColor2;
uniform vec3 u_directionToLight2;
#endif
#ifdef THREE_LIGHTS
uniform vec3 u_ambientLightColor;
uniform vec3 u_diffuseLightColor1;
uniform vec3 u_directionToLight1;
uniform vec3 u_diffuseLightColor2;
uniform vec3 u_directionToLight2;
uniform vec3 u_diffuseLightColor3;
uniform vec3 u_directionToLight3;
#endif

// Fog
#ifdef USE_FOG
uniform float u_fogStart;
uniform float u_fogLength;
#endif

// Inputs and outputs
attribute vec3 a_position;
#ifdef USE_LIGHTING
attribute vec3 a_normal;
#endif
#ifdef USE_VERTEXCOLOR
attribute vec4 a_color;
#endif
#ifdef USE_TEXTURE
attribute vec2 a_texcoord;
#endif
#ifdef USE_INSTANCING
attribute float a_instance;
#endif
varying vec4 v_color;
#ifdef USE_TEXTURE
varying vec2 v_texcoord;
#endif
#ifdef USE_FOG
varying float v_fog;
#endif

void SCVert()
{
	// Texture
#ifdef USE_TEXTURE
	v_texcoord = a_texcoord;
#endif

	// Instancing
#ifdef USE_INSTANCING
	int instance = int(a_instance);
#endif

	// Normal
#ifdef USE_LIGHTING
#ifdef USE_INSTANCING
	vec3 worldNormal = normalize(vec3(u_worldMatrix[instance] * vec4(a_normal, 0.0)));
#else
	vec3 worldNormal = normalize(vec3(u_worldMatrix * vec4(a_normal, 0.0)));
#endif
#endif

	// Lighting
#ifndef USE_LIGHTING
	v_color = u_materialColor;
#endif
#ifdef ONE_LIGHT
	vec3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	v_color = vec4(lightColor, 1) * u_materialColor;
#endif
#ifdef TWO_LIGHTS
	vec3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	lightColor += u_diffuseLightColor2 * max(dot(u_directionToLight2, worldNormal), 0.0);
	v_color = vec4(lightColor, 1) * u_materialColor;
#endif
#ifdef THREE_LIGHTS
	vec3 lightColor = u_ambientLightColor;
	lightColor += u_diffuseLightColor1 * max(dot(u_directionToLight1, worldNormal), 0.0);
	lightColor += u_diffuseLightColor2 * max(dot(u_directionToLight2, worldNormal), 0.0);
	lightColor += u_diffuseLightColor3 * max(dot(u_directionToLight3, worldNormal), 0.0);
	v_color = vec4(lightColor, 1) * u_materialColor;
#endif

	// Vertex color
#ifdef USE_VERTEXCOLOR
	v_color *= a_color;
#endif

	// Emission color
#ifdef USE_EMISSIONCOLOR
	v_color += u_emissionColor;
#endif

	// Fog
#ifdef USE_FOG
#ifdef USE_INSTANCING
	vec3 viewPosition = vec3(u_worldViewMatrix[instance] * vec4(a_position, 1.0));
#else
	vec3 viewPosition = vec3(u_worldViewMatrix * vec4(a_position, 1.0));
#endif
	float d = length(viewPosition);
	v_fog = clamp((d - u_fogStart) / u_fogLength, 0.0, 1.0);
#endif

	// Position
#ifdef USE_INSTANCING
	gl_Position = u_worldViewProjectionMatrix[instance] * vec4(a_position, 1.0);
#else
	gl_Position = u_worldViewProjectionMatrix * vec4(a_position, 1.0);
#endif

	// Fix gl_Position
	OPENGL_POSITION_FIX;
}

#endif

#endif
#if defined(SHADER_STAGE_FRAGMENT)
#ifdef HLSL

#ifdef USE_TEXTURE
Texture2D u_texture;
SamplerState sampler_u_texture;
#endif
#ifdef USE_ALPHATHRESHOLD
float u_alphaThreshold;
#endif
#ifdef USE_FOG
float3 u_fogColor;
#endif

void SCFrag(
	in float4 v_color : COLOR,
#ifdef USE_TEXTURE
	in float2 v_texcoord: TEXCOORD,
#endif
#ifdef USE_FOG
	in float v_fog : FOG,
#endif
	out float4 svTarget: SV_TARGET
)
{
	// Color
	float4 result = v_color;

	// Texture
#ifdef USE_TEXTURE
	result *= u_texture.Sample(sampler_u_texture, v_texcoord);
#endif

	// Alpha threshold
#ifdef USE_ALPHATHRESHOLD
	if (result.a <= u_alphaThreshold)
		discard;
#endif

	// Fog
#ifdef USE_FOG
	float4 premultipliedFogColor = float4(u_fogColor * result.a, result.a);
	result = lerp(result, premultipliedFogColor, v_fog);
#endif

	// Return
	svTarget = result;
}

#endif
#ifdef GLSL

// <Sampler Name='sampler_u_texture' Texture='u_texture' />

#ifdef GL_ES
precision mediump float;
#endif

#ifdef USE_TEXTURE
uniform sampler2D u_texture;
#endif
#ifdef USE_ALPHATHRESHOLD
uniform float u_alphaThreshold;
#endif
#ifdef USE_FOG
uniform vec3 u_fogColor;
#endif

varying vec4 v_color;
#ifdef USE_TEXTURE
varying vec2 v_texcoord;
#endif
#ifdef USE_FOG
varying float v_fog;
#endif

void SCFrag()
{
	// Color
	vec4 result = v_color;

	// Texture
#ifdef USE_TEXTURE
	result *= texture2D(u_texture, v_texcoord);
#endif

	// Alpha threshold
#ifdef USE_ALPHATHRESHOLD
	if (result.a <= u_alphaThreshold)
		discard;
#endif

	// Fog
#ifdef USE_FOG
	vec4 premultipliedFogColor = vec4(u_fogColor * result.a, result.a);
	result = mix(result, premultipliedFogColor, v_fog);
#endif

	// On some devices using gl_FragColor in calculations causes a compile fail (Kindle Fire 1)
	gl_FragColor = result;
}

#endif

#endif
ENDHLSL
} }
}
